import React, { useEffect, useMemo, useRef, useState } from 'react'
import * as THREE from 'three'
import { Pause, Play, RotateCcw, X, AlertTriangle, ScanLine, CheckCircle2, Focus, Camera } from 'lucide-react'

const COLORS={car:0x4aa3ff,bike:0xffd166,auto:0x35d07f,bus:0xff6b6b,truck:0xb889ff,van:0x66d9ef}
const mat=(c,r=.55)=>new THREE.MeshStandardMaterial({color:c,metalness:.18,roughness:r})
function wheel(r=.34,w=.18){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,w,18),mat(0x050607,.9));m.rotation.x=Math.PI/2;return m}
function vehicle(kind,ego=false){
 const g=new THREE.Group(), c=ego?0x00e5ff:(COLORS[kind]||0xe8edf4)
 const dims=kind==='bus'?[10.6,2.65,2.45]:kind==='truck'?[8.8,2.35,2.35]:kind==='van'?[5.1,1.65,1.95]:kind==='auto'?[2.75,1.45,1.4]:kind==='bike'?[1.5,.75,.42]:[4.4,1.25,1.78]
 const body=new THREE.Mesh(new THREE.BoxGeometry(...dims),mat(c));body.position.y=dims[1]/2+.35;g.add(body)
 if(kind==='car'||kind==='van'){const cab=new THREE.Mesh(new THREE.BoxGeometry(dims[0]*.5,.6,dims[2]*.86),mat(0x091722,.2));cab.position.set(-.15,dims[1]+.25,0);g.add(cab)}
 if(kind==='auto'){const roof=new THREE.Mesh(new THREE.BoxGeometry(1.7,.55,1.35),mat(0x101813,.7));roof.position.set(-.3,1.65,0);g.add(roof)}
 if(kind==='bike'){const rider=new THREE.Mesh(new THREE.CapsuleGeometry(.18,.55,4,8),mat(0xe8edf4));rider.position.set(0,1.25,0);rider.rotation.z=-.2;g.add(rider);const head=new THREE.Mesh(new THREE.SphereGeometry(.18,12,12),mat(0x202a35));head.position.set(.15,1.72,0);g.add(head)}
 const axle=kind==='bus'?[-3.5,3.4]:kind==='truck'?[-2.7,2.5]:[-Math.max(.65,dims[0]*.3),Math.max(.65,dims[0]*.3)]
 for(const x of axle)for(const z of [-dims[2]/2-.04,dims[2]/2+.04]){const w=wheel(kind==='bus'||kind==='truck'?.46:.31);w.position.set(x,.38,z);g.add(w)}
 if(ego){const ring=new THREE.Mesh(new THREE.RingGeometry(3,3.4,54),new THREE.MeshBasicMaterial({color:0x00e5ff,transparent:true,opacity:.65,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.04;g.add(ring);const beam=new THREE.Mesh(new THREE.ConeGeometry(4,18,32,1,true),new THREE.MeshBasicMaterial({color:0x00e5ff,transparent:true,opacity:.045,side:THREE.DoubleSide}));beam.rotation.z=-Math.PI/2;beam.position.set(10,1.2,0);g.add(beam)}
 g.userData.target=new THREE.Vector3();return g
}
function pothole(){const g=new THREE.Group();const pit=new THREE.Mesh(new THREE.CylinderGeometry(1.15,.8,.13,22),mat(0x050505,1));pit.scale.z=.55;pit.position.y=.02;g.add(pit);const rim=new THREE.Mesh(new THREE.RingGeometry(.9,1.35,24),new THREE.MeshBasicMaterial({color:0x6d3f27,transparent:true,opacity:.85,side:THREE.DoubleSide}));rim.rotation.x=-Math.PI/2;rim.scale.y=.55;rim.position.y=.09;g.add(rim);return g}
function water(){const m=new THREE.Mesh(new THREE.CircleGeometry(2.4,30),new THREE.MeshStandardMaterial({color:0x246d89,transparent:true,opacity:.58,roughness:.18}));m.rotation.x=-Math.PI/2;m.scale.y=.48;m.position.y=.1;return m}
function detectionBeacon(color=0xff4258){const g=new THREE.Group();for(const r of [1.8,2.6,3.4]){const ring=new THREE.Mesh(new THREE.RingGeometry(r,r+.08,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.userData.base=r;g.add(ring)}const post=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,3.6,8),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.72}));post.position.y=1.8;g.add(post);g.userData.pulse=0;return g}
function trackingHalo(){const g=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(2.4,.08,10,48),new THREE.MeshBasicMaterial({color:0xff304e}));ring.rotation.x=Math.PI/2;ring.position.y=.15;g.add(ring);const box=new THREE.Mesh(new THREE.BoxGeometry(5.2,2.8,2.5),new THREE.MeshBasicMaterial({color:0xff304e,wireframe:true,transparent:true,opacity:.75}));box.position.y=1.45;g.add(box);g.userData.pulse=0;return g}

export default function BusMicroTwin({bus,onClose}){
 const mountRef=useRef(null), sceneRef=useRef(null), cameraRef=useRef(null), meshes=useRef(new Map()), scenery=useRef([]), hazards=useRef(new Map()), beacons=useRef(new Map()), trackers=useRef(new Map()), triggered=useRef(new Set()), alertTimer=useRef(null)
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(null),[playing,setPlaying]=useState(true),[frameIndex,setFrameIndex]=useState(0),[cameraMode,setCameraMode]=useState('chase'),[playbackRate,setPlaybackRate]=useState(1),[activeEvent,setActiveEvent]=useState(null),[eventLog,setEventLog]=useState([]),[analysisPhase,setAnalysisPhase]=useState(null),[rashTarget,setRashTarget]=useState(null)
 useEffect(()=>{let dead=false;setLoading(true);setError(null);fetch(`/api/v2/sumo/bus/${bus.bus_id}`).then(r=>r.json()).then(p=>{if(dead)return;if(!p.available)throw Error(p.reason||'SUMO unavailable');setData(p);setFrameIndex(0);setLoading(false)}).catch(e=>{if(!dead){setError(e.message);setLoading(false)}});return()=>{dead=true}},[bus.bus_id])
 useEffect(()=>{if(!data||!mountRef.current)return;const mount=mountRef.current,scene=new THREE.Scene();scene.background=new THREE.Color(0x05070a);scene.fog=new THREE.Fog(0x05070a,90,260);const cam=new THREE.PerspectiveCamera(52,mount.clientWidth/mount.clientHeight,.1,1000);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(mount.clientWidth,mount.clientHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;mount.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0x9fdcff,0x101018,1.55));const sun=new THREE.DirectionalLight(0xffffff,2.1);sun.position.set(-10,30,20);scene.add(sun)
 const road=new THREE.Mesh(new THREE.BoxGeometry(250,.15,12.5),mat(0x171a20,.98));scene.add(road)
 for(const z of [-2.05,2.05])for(let x=-126;x<=126;x+=7){const d=new THREE.Mesh(new THREE.BoxGeometry(3.6,.03,.09),new THREE.MeshBasicMaterial({color:0xc9d0da}));d.position.set(x,.1,z);scene.add(d);scenery.current.push(d)}
 for(let x=-120;x<=120;x+=20)for(const z of [-8.5,8.5]){const pole=new THREE.Mesh(new THREE.CylinderGeometry(.08,.11,5.5,10),mat(0x26313c,.85));pole.position.set(x,2.75,z);scene.add(pole);scenery.current.push(pole)}
 for(const s of data.scenarios||[]){let h=s.type==='ROAD_DEFECT'?pothole():s.type==='ROAD_HAZARD'?water():null;if(h){scene.add(h);hazards.current.set(s.id,h)}const b=detectionBeacon(s.type==='DRIVING_ANOMALY'?0xff3150:s.type==='ROAD_DEFECT'?0xffa52f:0x34d9ff);b.visible=false;scene.add(b);beacons.current.set(s.id,b)}
 sceneRef.current=scene;cameraRef.current=cam;let raf;const clock=new THREE.Clock();const render=()=>{const dt=clock.getDelta();meshes.current.forEach(m=>m.position.lerp(m.userData.target,.2));beacons.current.forEach(b=>{if(!b.visible)return;b.userData.pulse+=dt*3.2;b.children.forEach((c,i)=>{if(c.geometry?.type==='RingGeometry'){const s=1+((Math.sin(b.userData.pulse-i*.7)+1)*.16);c.scale.set(s,s,s);c.material.opacity=.35+.45*((Math.sin(b.userData.pulse-i*.8)+1)/2)}})});trackers.current.forEach(t=>{t.userData.pulse+=dt*4;t.scale.setScalar(1+Math.sin(t.userData.pulse)*.04)});renderer.render(scene,cam);raf=requestAnimationFrame(render)};render();const resize=()=>{cam.aspect=mount.clientWidth/mount.clientHeight;cam.updateProjectionMatrix();renderer.setSize(mount.clientWidth,mount.clientHeight)};addEventListener('resize',resize);return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize);if(alertTimer.current)clearTimeout(alertTimer.current);renderer.dispose();if(renderer.domElement.parentNode===mount)mount.removeChild(renderer.domElement);meshes.current.clear();scenery.current=[];hazards.current.clear();beacons.current.clear();trackers.current.clear()}},[data])
 useEffect(()=>{if(!data?.frames?.length||!sceneRef.current)return;const f=data.frames[Math.min(frameIndex,data.frames.length-1)],ego=f.ego,egoX=ego?.x||0,active=new Set();for(const v of f.vehicles){active.add(v.id);let m=meshes.current.get(v.id);if(!m){m=vehicle(v.kind,v.ego);meshes.current.set(v.id,m);sceneRef.current.add(m);m.position.set(v.x-egoX,.12,(v.lane-1)*4.1)}m.userData.target.set(v.x-egoX,.12,(v.lane-1)*4.1)}meshes.current.forEach((m,id)=>{if(!active.has(id)){sceneRef.current.remove(m);meshes.current.delete(id)}})
 scenery.current.forEach((o,i)=>{const base=-120+(i%13)*20;o.position.x=((base-egoX+125)%250)-125})
 for(const s of data.scenarios||[]){const h=hazards.current.get(s.id);if(h)h.position.set(s.x-egoX,.1,(s.lane-1)*4.1);const b=beacons.current.get(s.id);if(b)b.position.set(s.x-egoX,.11,(s.lane-1)*4.1)}
 const candidates=(data.scenarios||[]).map(s=>({...s,dx:ego?s.x-egoX:999})).filter(s=>s.dx<58&&s.dx>-55).sort((a,b)=>Math.abs(a.dx)-Math.abs(b.dx));const current=candidates[0]||null
 if(current){let phase=current.dx>32?'SCANNING':current.dx>18?'CANDIDATE LOCK':current.dx>5?'CLASSIFYING':current.dx>-12?'EVIDENCE LOCKED':'PASSED · EVENT PERSISTED';setAnalysisPhase(phase);const beacon=beacons.current.get(current.id);if(beacon)beacon.visible=true
  if(!triggered.current.has(current.id)&&current.dx<28){triggered.current.add(current.id);setActiveEvent(current);setEventLog(log=>[current,...log.filter(x=>x.id!==current.id)].slice(0,5));if(alertTimer.current)clearTimeout(alertTimer.current);alertTimer.current=setTimeout(()=>setActiveEvent(prev=>prev?.id===current.id?null:prev),8500)}
  if(current.type==='DRIVING_ANOMALY'&&current.dx<34&&current.dx>-30){const possible=(f.vehicles||[]).filter(v=>!v.ego&&['car','auto','bike','van'].includes(v.kind)&&v.x>egoX-8).sort((a,b)=>Math.abs((a.x-egoX)-18)-Math.abs((b.x-egoX)-18));const target=possible[0];if(target){setRashTarget(target.id);let tr=trackers.current.get(target.id);const vm=meshes.current.get(target.id);if(!tr&&vm){tr=trackingHalo();vm.add(tr);trackers.current.set(target.id,tr)}}}
 }else{setAnalysisPhase(activeEvent?'EVENT STORED · MONITORING CONTINUES':null)}
 if(cameraRef.current){if(cameraMode==='top'){cameraRef.current.position.set(0,72,.01);cameraRef.current.lookAt(0,0,0)}else if(cameraMode==='pov'){cameraRef.current.position.set(-4.6,3.4,0);cameraRef.current.lookAt(32,1.2,0)}else{cameraRef.current.position.set(-29,19,24);cameraRef.current.lookAt(9,0,0)}}},[data,frameIndex,cameraMode,activeEvent])
 useEffect(()=>{if(!playing||!data?.frames?.length)return;const cinematic=!!analysisPhase&&analysisPhase!=='EVENT STORED · MONITORING CONTINUES';const baseDelay=cinematic?230:110;const t=setInterval(()=>setFrameIndex(i=>(i+1)%data.frames.length),baseDelay/playbackRate);return()=>clearInterval(t)},[playing,data,analysisPhase,playbackRate])
 const frame=data?.frames?.[frameIndex],ego=frame?.ego,counts=useMemo(()=>{const o={};for(const v of frame?.vehicles||[])o[v.kind]=(o[v.kind]||0)+1;return o},[frame])
 const progress=ego?Math.min(100,(ego.x/data?.road_length_m)*100):0
 return <div className="micro-twin-overlay"><div className="micro-twin-shell">
  <div className="micro-twin-head"><div><span>PRAYAAN · SUMO URBAN INTELLIGENCE TWIN</span><h2>{bus.bus_id} · Live Mission Replay</h2></div><div className="micro-actions"><div className="micro-speed-switch">{[0.5,1,2].map(rate=><button key={rate} className={playbackRate===rate?'active':''} onClick={()=>setPlaybackRate(rate)}>{rate}×</button>)}</div><div className="micro-camera-switch">{['chase','pov','top'].map(m=><button key={m} className={cameraMode===m?'active':''} onClick={()=>setCameraMode(m)}>{m.toUpperCase()}</button>)}</div><button onClick={()=>setPlaying(x=>!x)}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><button onClick={()=>{setFrameIndex(0);setPlaybackRate(1);setEventLog([]);setActiveEvent(null);setAnalysisPhase(null);setRashTarget(null);triggered.current.clear();beacons.current.forEach(b=>b.visible=false)}}><RotateCcw size={17}/></button><button onClick={onClose}><X size={18}/></button></div></div>
  {loading&&<div className="micro-loading">Generating SUMO physics + mission scenarios for {bus.bus_id}…</div>}{error&&<div className="micro-error"><b>SUMO micro twin unavailable</b><span>{error}</span></div>}
  {data&&<><div ref={mountRef} className="micro-canvas"/>
   <div className="analysis-status"><span className={analysisPhase?'live':''}><Focus size={14}/>{analysisPhase||'PASSIVE SCAN'}</span><b>{playbackRate}× PLAYBACK{analysisPhase?' · CINEMATIC ANALYSIS':''}</b></div>
   <div className="micro-hud left"><span>PHYSICS</span><b>LIVE SUMO FCD</b><small>IDM · LC2013 · seed {data.seed}</small><small>Scenario input: SYNTHETIC · analytics: LIVE</small></div>
   <div className="micro-hud right"><span>EGO BUS</span><b>{ego?`${(ego.speed*3.6).toFixed(1)} km/h`:'entering corridor'}</b><small>{frame?.local_density||0} nearby · {frame?.stopped_vehicles||0} stopped</small><small>travelled {ego?ego.x.toFixed(0):0} / {data.road_length_m} m</small></div>
   <div className="micro-types">{Object.entries(counts).map(([k,n])=><span key={k}>{k.toUpperCase()} <b>{n}</b></span>)}</div>
   <div className="scenario-stack"><div className="scenario-stack-title">MISSION EVIDENCE · PERSISTENT</div>{eventLog.map(e=><div className={`scenario-mini ${e.severity.toLowerCase()}`} key={e.id}><CheckCircle2 size={13}/><div><b>{e.label}</b><small>{Math.round(e.confidence*100)}% · STORED</small>{e.plate&&<small>{e.plate} · ANPR {Math.round(e.plate_confidence*100)}%</small>}</div></div>)}</div>
   {activeEvent&&<div className={`scenario-alert persistent ${activeEvent.severity.toLowerCase()}`}><div className="scenario-alert-top"><ScanLine size={19}/><span>EDGE AI INCIDENT ANALYSIS</span><b>{activeEvent.label}</b></div><div className="analysis-steps"><span className="done">01 DETECT</span><span className={analysisPhase&&analysisPhase!=='SCANNING'?'done':''}>02 TRACK</span><span className={['CLASSIFYING','EVIDENCE LOCKED','PASSED · EVENT PERSISTED','EVENT STORED · MONITORING CONTINUES'].includes(analysisPhase)?'done':''}>03 CLASSIFY</span><span className={['EVIDENCE LOCKED','PASSED · EVENT PERSISTED','EVENT STORED · MONITORING CONTINUES'].includes(analysisPhase)?'done':''}>04 PACKAGE</span></div><p>{activeEvent.detail}</p><div className="scenario-evidence"><span>CONFIDENCE <b>{Math.round(activeEvent.confidence*100)}%</b></span><span>SEVERITY <b>{activeEvent.severity}</b></span>{activeEvent.plate&&<span>ANPR <b>{activeEvent.plate}</b> · {Math.round(activeEvent.plate_confidence*100)}%</span>}</div>{activeEvent.type==='DRIVING_ANOMALY'&&<div className="track-lock"><Camera size={15}/><span>VEHICLE TRACK</span><b>{rashTarget||'ACQUIRING...'}</b><i>LOCKED</i></div>}<small>{activeEvent.action}</small><div className="alert-persist-note">Evidence panel remains visible after the physical encounter so the operator can inspect the result.</div></div>}
   <div className="scenario-route"><span className="route-progress" style={{width:`${progress}%`}}/><span className="scenario-marker p" style={{left:'22%'}}>POTHOLE</span><span className="scenario-marker r" style={{left:'48%'}}>RASH + ANPR</span><span className="scenario-marker w" style={{left:'76%'}}>WATERLOGGING</span></div>
   <div className="micro-timeline"><i style={{width:`${((frameIndex+1)/data.frames.length)*100}%`}}/></div>
  </>}</div></div>
}
